name: tome-wishlist-downloader
services:
  tome-wishlist-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tome-wishlist-downloader
    env_file:
      - .env
    environment:
      - ZLIB_DOWNLOAD_DIR=/downloads
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped