name: wishflow
services:
  tome-wishlist-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tome-wishlist-downloader
    env_file:
      - .env
    environment:
      - ZLIB_DOWNLOAD_DIR=/downloads
      - SCHEDULE_DB=/data/schedule.db
    volumes:
      - ./downloads:/downloads
      - ./data:/data
    restart: unless-stopped